/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.GalponController;
import View.Table.TableGalpon;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;

/**
 *
 * @author Home
 */
public class Frm_Galpon extends javax.swing.JFrame {

    private GalponController galponController = new GalponController();
    private TableGalpon modelo = new TableGalpon();

    /**
     * Creates new form Frm_Galpon
     */
    public Frm_Galpon() {
        super("Registro de Galpones");
        setResizable(false);
        initComponents();
        setLocationRelativeTo(null);
        limpiardatos();
        poputTable();
    }
        public void poputTable() {
        JPopupMenu popuMenu = new JPopupMenu();
        JMenuItem menuItem1 = new JMenuItem("Aplicar Vacuna", new ImageIcon(getClass().getResource("/Image/vacuna.png")));
        menuItem1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Frm_Vacunas vacunas = new Frm_Vacunas();
                int fila = tablegalpon.getSelectedRow();
                vacunas.setVisible(true);
                dispose();
                Frm_Vacunas.txtnum.setText(tablegalpon.getValueAt(fila, 0).toString());
            }
        });
        popuMenu.add(menuItem1);
        tablegalpon.setComponentPopupMenu(popuMenu);
    }
    private void cargarTable() {
        modelo.setLista(galponController.listar());
        tablegalpon.setModel(modelo);
        tablegalpon.updateUI();
    }
    private void limpiardatos() {
        txtnumeropollo.setText(" ");
        txtraza.setText(" ");
        txtpeso.setText(" ");
        txtmuestra.setText(" ");
        galponController.setGalpon(null);
        cargarTable();
    }
    private void guardar() {
        if (txtnumeropollo.getText().trim().isEmpty() || txtraza.getText().trim().isEmpty()
                || txtpeso.getText().trim().isEmpty() || txtmuestra.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Llene todos los campos", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            galponController.getGalpon().setNumPollo(Integer.parseInt(txtnumeropollo.getText()));
            galponController.getGalpon().setRaza(txtraza.getText());
            galponController.getGalpon().setPeso(Double.parseDouble(txtpeso.getText()));
            galponController.getGalpon().setMuestra(Double.parseDouble(txtmuestra.getText()));
            if (galponController.getGalpon().getId() == null) {
                if (galponController.Save()) {
                    JOptionPane.showMessageDialog(null, "Se guardo` correctamente", "Ok", JOptionPane.INFORMATION_MESSAGE);
                    limpiardatos();
                } else {
                    JOptionPane.showMessageDialog(null, "Error al guardar", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
            //ciudadController.getCiudad().setId(new Long(ciudadController.listar().tamanio() + 1));
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtnumeropollo = new javax.swing.JTextField();
        txtmuestra = new javax.swing.JTextField();
        txtpeso = new javax.swing.JTextField();
        txtraza = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablegalpon = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTRO DE GALPONES");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(100, 6, 240, 20);

        jPanel2.add(jPanel1);
        jPanel1.setBounds(10, 10, 470, 30);

        jPanel3.setBackground(new java.awt.Color(255, 204, 51));
        jPanel3.setLayout(null);

        jLabel2.setText("Muestra");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(350, 10, 50, 16);

        jLabel3.setText("Numero de Pollos");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(10, 10, 110, 16);

        jLabel4.setText("Raza");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(140, 10, 40, 16);

        jLabel5.setText("Peso");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(250, 10, 40, 16);
        jPanel3.add(txtnumeropollo);
        txtnumeropollo.setBounds(20, 30, 60, 24);
        jPanel3.add(txtmuestra);
        txtmuestra.setBounds(340, 30, 70, 24);
        jPanel3.add(txtpeso);
        txtpeso.setBounds(230, 30, 60, 24);
        jPanel3.add(txtraza);
        txtraza.setBounds(120, 30, 74, 24);

        jPanel4.setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/acualizar.png"))); // NOI18N
        jPanel4.add(jButton1);
        jButton1.setBounds(10, 70, 57, 50);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/eliminar.png"))); // NOI18N
        jPanel4.add(jButton2);
        jButton2.setBounds(10, 130, 57, 50);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/guardar.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3);
        jButton3.setBounds(10, 10, 57, 50);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(10, 70, 80, 200);

        tablegalpon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablegalpon);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(100, 70, 360, 200);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(10, 50, 470, 280);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 490, 340);

        setSize(new java.awt.Dimension(502, 371));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        guardar();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Galpon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Galpon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Galpon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Galpon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Galpon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablegalpon;
    private javax.swing.JTextField txtmuestra;
    private javax.swing.JTextField txtnumeropollo;
    private javax.swing.JTextField txtpeso;
    private javax.swing.JTextField txtraza;
    // End of variables declaration//GEN-END:variables
}
