/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;

/**
 *
 * @author John
 */
public class Frm_impresion_factura extends javax.swing.JPanel implements Printable {

    /**
     * Creates new form Frm_impresion_factura
     */
    public Frm_impresion_factura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLRuc1 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLCodigoA1 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLDireccion1 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLTelefono1 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLCorreoElectronico1 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTDateF = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTNombreF = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jTDireccionF = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jTCIF = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jTelefonoF = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableFacturaImprimir = new javax.swing.JTable();
        jLabel33 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel34 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jTSubtotalF = new javax.swing.JTextField();
        jTDescuentoF = new javax.swing.JTextField();
        jTtotalF = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jTIva0F = new javax.swing.JTextField();
        jTIVA12F = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(489, 631));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(null);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel20.setText("AVICOLA SAN ANTONIO");
        jPanel7.add(jLabel20);
        jLabel20.setBounds(170, 10, 300, 30);

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel21.setText("SALINAS CUEVA LENIN RENE");
        jPanel7.add(jLabel21);
        jLabel21.setBounds(210, 40, 210, 20);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel22.setText("VENTA AL POR MENOR Y MAYOR DE ANIMALES DE CORRAL");
        jPanel7.add(jLabel22);
        jLabel22.setBounds(170, 60, 280, 10);

        jLabel24.setText("RUC:");
        jPanel7.add(jLabel24);
        jLabel24.setBounds(30, 90, 90, 20);

        jLRuc1.setText("1716579451001");
        jPanel7.add(jLRuc1);
        jLRuc1.setBounds(80, 90, 130, 20);

        jLabel25.setText("Codigo  Autorizacion:");
        jPanel7.add(jLabel25);
        jLabel25.setBounds(30, 110, 110, 20);

        jLCodigoA1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLCodigoA1.setText("1122233877");
        jPanel7.add(jLCodigoA1);
        jLCodigoA1.setBounds(140, 110, 110, 20);

        jLabel26.setText("Direccion:");
        jPanel7.add(jLabel26);
        jLabel26.setBounds(30, 140, 80, 10);

        jLDireccion1.setText("San Jose/ San Antonio de las Aradas");
        jPanel7.add(jLDireccion1);
        jLDireccion1.setBounds(90, 140, 230, 10);

        jLabel27.setText("Telefono:");
        jPanel7.add(jLabel27);
        jLabel27.setBounds(30, 160, 60, 10);

        jLTelefono1.setText("0997793377");
        jPanel7.add(jLTelefono1);
        jLTelefono1.setBounds(90, 160, 100, 14);

        jLabel28.setText("Correo  Electronico:");
        jPanel7.add(jLabel28);
        jLabel28.setBounds(30, 180, 120, 14);

        jLCorreoElectronico1.setText("leninsa_18@hotmail.com");
        jPanel7.add(jLCorreoElectronico1);
        jLCorreoElectronico1.setBounds(160, 180, 140, 20);

        jLabel23.setText("FECHA  DE  EMISION");
        jPanel7.add(jLabel23);
        jLabel23.setBounds(410, 90, 130, 20);
        jPanel7.add(jTDateF);
        jTDateF.setBounds(410, 120, 100, 30);

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel29.setText("CLIENTE:");
        jPanel7.add(jLabel29);
        jLabel29.setBounds(30, 220, 60, 14);
        jPanel7.add(jSeparator1);
        jSeparator1.setBounds(110, 240, 470, 10);

        jTNombreF.setBorder(null);
        jPanel7.add(jTNombreF);
        jTNombreF.setBounds(110, 210, 470, 30);

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel30.setText("DIRECCION:");
        jPanel7.add(jLabel30);
        jLabel30.setBounds(30, 260, 80, 14);
        jPanel7.add(jSeparator2);
        jSeparator2.setBounds(110, 280, 470, 10);

        jTDireccionF.setBorder(null);
        jPanel7.add(jTDireccionF);
        jTDireccionF.setBounds(110, 250, 470, 40);

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel31.setText("R.U.C./C.I.:");
        jPanel7.add(jLabel31);
        jLabel31.setBounds(30, 310, 70, 20);
        jPanel7.add(jSeparator3);
        jSeparator3.setBounds(110, 330, 280, 10);

        jTCIF.setBorder(null);
        jPanel7.add(jTCIF);
        jTCIF.setBounds(110, 300, 290, 40);

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel32.setText("TELEFONO:");
        jPanel7.add(jLabel32);
        jLabel32.setBounds(400, 310, 70, 20);
        jPanel7.add(jSeparator4);
        jSeparator4.setBounds(470, 330, 110, 10);

        jTelefonoF.setBorder(null);
        jTelefonoF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTelefonoFActionPerformed(evt);
            }
        });
        jPanel7.add(jTelefonoF);
        jTelefonoF.setBounds(470, 300, 110, 40);

        jTableFacturaImprimir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTableFacturaImprimir.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CANT.", "DESCRIPCION", "P.UNITARIO", "P.TOTAL"
            }
        ));
        jScrollPane2.setViewportView(jTableFacturaImprimir);

        jPanel7.add(jScrollPane2);
        jScrollPane2.setBounds(30, 350, 550, 160);

        jLabel33.setText("FIRMA    AUTORIZADA");
        jPanel7.add(jLabel33);
        jLabel33.setBounds(80, 730, 130, 20);
        jPanel7.add(jSeparator5);
        jSeparator5.setBounds(60, 730, 140, 10);

        jLabel34.setText("FIRMA   CLIENTE");
        jPanel7.add(jLabel34);
        jLabel34.setBounds(410, 730, 110, 20);
        jPanel7.add(jSeparator6);
        jSeparator6.setBounds(390, 730, 110, 10);

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel35.setText("SUBTOTAL");
        jLabel35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.add(jLabel35);
        jLabel35.setBounds(310, 510, 130, 30);

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel36.setText("Descuento");
        jLabel36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.add(jLabel36);
        jLabel36.setBounds(310, 540, 130, 30);

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel37.setText("TOTAL");
        jLabel37.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.add(jLabel37);
        jLabel37.setBounds(310, 630, 130, 30);
        jPanel7.add(jTSubtotalF);
        jTSubtotalF.setBounds(440, 510, 140, 30);
        jPanel7.add(jTDescuentoF);
        jTDescuentoF.setBounds(440, 540, 140, 30);
        jPanel7.add(jTtotalF);
        jTtotalF.setBounds(440, 630, 140, 30);
        jPanel7.add(jSeparator7);
        jSeparator7.setBounds(410, 110, 100, 10);

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel38.setText("IVA 0%");
        jLabel38.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.add(jLabel38);
        jLabel38.setBounds(310, 570, 130, 30);

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel39.setText("IVA 12%");
        jLabel39.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.add(jLabel39);
        jLabel39.setBounds(310, 600, 130, 30);
        jPanel7.add(jTIva0F);
        jTIva0F.setBounds(440, 570, 140, 30);
        jPanel7.add(jTIVA12F);
        jTIVA12F.setBounds(440, 600, 140, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 679, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 762, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTelefonoFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTelefonoFActionPerformed
    }//GEN-LAST:event_jTelefonoFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLCodigoA1;
    private javax.swing.JLabel jLCorreoElectronico1;
    private javax.swing.JLabel jLDireccion1;
    private javax.swing.JLabel jLRuc1;
    private javax.swing.JLabel jLTelefono1;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField jTCIF;
    private javax.swing.JTextField jTDateF;
    private javax.swing.JTextField jTDescuentoF;
    private javax.swing.JTextField jTDireccionF;
    private javax.swing.JTextField jTIVA12F;
    private javax.swing.JTextField jTIva0F;
    private javax.swing.JTextField jTNombreF;
    private javax.swing.JTextField jTSubtotalF;
    private javax.swing.JTable jTableFacturaImprimir;
    private javax.swing.JTextField jTelefonoF;
    private javax.swing.JTextField jTtotalF;
    // End of variables declaration//GEN-END:variables
    /**
     * Este metodo se encarga de transformar al formulario de JPanel a un tipo
     * graphics para su uso en los metodos de impresion
     *
     * @param graphics
     * @param pageFormat
     * @param pageIndex
     * @return existencia de page (graphics2d)
     * @throws PrinterException
     */
    @Override
    public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
        if (pageIndex == 0) {
            Graphics2D graphics2d = (Graphics2D) graphics;
            graphics2d.translate(pageFormat.getImageableX(), pageFormat.getImageableY());
            printAll(graphics2d);
            return PAGE_EXISTS;
        } else {
            return NO_SUCH_PAGE;
        }
    }
}
