/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import Controller.GalponController;
import Controller.VacunaController;
import View.Table.TableGalpon;
import View.Table.TableVacuna;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.Document;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;
import javax.swing.SwingConstants;
import javax.swing.event.DocumentListener;
import javax.swing.event.UndoableEditListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.Element;
import javax.swing.text.Position;
import javax.swing.text.Segment;

/**
 *
 * @author JavierSarango
 */
public class Frm_PrincipalDemo extends javax.swing.JDialog {

    fondoPaneles paneles = new fondoPaneles();
    fondoLabel logotipo = new fondoLabel();
    private DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
    private VacunaController vacunaController = new VacunaController();
    private TableVacuna modelov = new TableVacuna();
    int xmouse, ymouse;
    public GalponController galponController = new GalponController();
    private TableGalpon modeloG = new TableGalpon();

    /**
     * Creates new form Seguimiento
     */
    public Frm_PrincipalDemo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        txtid.setVisible(false);
        poputTable();
        cargarTableGalpon();
        cargarTableVacuna();
        txtidvacuna.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo1 = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        Cerrar = new javax.swing.JPanel();
        closetext = new javax.swing.JLabel();
        Navegador = new javax.swing.JPanel();
        Title = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BtnRegistroGalpon = new javax.swing.JPanel();
        registroGalpontxt = new javax.swing.JLabel();
        JPVacuna = new javax.swing.JPanel();
        vacunatxt = new javax.swing.JLabel();
        Fondo2 = new javax.swing.JPanel();
        jPanelSlider1 = new diu.swe.habib.JPanelSlider.JPanelSlider();
        jPanel3 = new fondoPaneles();
        rSLabelHora1 = new rojeru_san.RSLabelHora();
        jLabel11 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        JLogotipo = new fondoLabel();
        jLabel21 = new javax.swing.JLabel();
        JPRegistroGalpones = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtnumeropollo = new javax.swing.JTextField();
        txtraza = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        btnGuardar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablegalpones = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        cbTipoBalanceado = new javax.swing.JComboBox<>();
        jSeparator8 = new javax.swing.JSeparator();
        txtCtdBalanceadoSuministrada = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbFDAlimentacion = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        JPRegistroVacuna = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtnombreProducto = new javax.swing.JTextField();
        jDate1 = new com.toedter.calendar.JDateChooser();
        jDate2 = new com.toedter.calendar.JDateChooser();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        cbTipoFarmaco = new javax.swing.JComboBox<>();
        txfGalponSeleccionado = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        JtaJustificacion = new javax.swing.JTextArea();
        txfDosis = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel26 = new javax.swing.JLabel();
        cbMedidaDosis = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablevacuna = new javax.swing.JTable();
        jButton8 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        txtidvacuna = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        Fondo1.setBackground(new java.awt.Color(255, 255, 255));
        Fondo1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Fondo1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        closetext.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        closetext.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closetext.setText("X");
        closetext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closetextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closetextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closetextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout CerrarLayout = new javax.swing.GroupLayout(Cerrar);
        Cerrar.setLayout(CerrarLayout);
        CerrarLayout.setHorizontalGroup(
            CerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(closetext, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );
        CerrarLayout.setVerticalGroup(
            CerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CerrarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(closetext, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(0, 1056, Short.MAX_VALUE)
                .addComponent(Cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(Cerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Fondo1.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 30));

        Navegador.setBackground(new java.awt.Color(102, 102, 255));
        Navegador.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Navegador.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setBackground(new java.awt.Color(102, 51, 255));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Control de Galpón");

        javax.swing.GroupLayout TitleLayout = new javax.swing.GroupLayout(Title);
        Title.setLayout(TitleLayout);
        TitleLayout.setHorizontalGroup(
            TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        TitleLayout.setVerticalGroup(
            TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Navegador.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, 50));

        BtnRegistroGalpon.setBackground(new java.awt.Color(102, 102, 255));
        BtnRegistroGalpon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnRegistroGalponMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnRegistroGalponMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnRegistroGalponMouseExited(evt);
            }
        });

        registroGalpontxt.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        registroGalpontxt.setForeground(new java.awt.Color(255, 255, 255));
        registroGalpontxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registroGalpontxt.setText("Registro Galpón");

        javax.swing.GroupLayout BtnRegistroGalponLayout = new javax.swing.GroupLayout(BtnRegistroGalpon);
        BtnRegistroGalpon.setLayout(BtnRegistroGalponLayout);
        BtnRegistroGalponLayout.setHorizontalGroup(
            BtnRegistroGalponLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registroGalpontxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        BtnRegistroGalponLayout.setVerticalGroup(
            BtnRegistroGalponLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BtnRegistroGalponLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(registroGalpontxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Navegador.add(BtnRegistroGalpon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 180, 40));

        JPVacuna.setBackground(new java.awt.Color(102, 102, 255));
        JPVacuna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPVacunaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPVacunaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPVacunaMouseExited(evt);
            }
        });

        vacunatxt.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        vacunatxt.setForeground(new java.awt.Color(255, 255, 255));
        vacunatxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vacunatxt.setText("Vacunas");

        javax.swing.GroupLayout JPVacunaLayout = new javax.swing.GroupLayout(JPVacuna);
        JPVacuna.setLayout(JPVacunaLayout);
        JPVacunaLayout.setHorizontalGroup(
            JPVacunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPVacunaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(vacunatxt, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );
        JPVacunaLayout.setVerticalGroup(
            JPVacunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vacunatxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Navegador.add(JPVacuna, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 190, 40));

        Fondo1.add(Navegador, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 210, 520));

        Fondo2.setLayout(null);

        jPanelSlider1.setBorder(null);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        rSLabelHora1.setForeground(new java.awt.Color(0, 0, 0));
        rSLabelHora1.setFont(new java.awt.Font("MS UI Gothic", 1, 48)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Dirección: Olmedo y Eugenio Espejo");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Teléfono de Contacto: 0959457834");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("Correo Electrónico: granjaavicola_sanatonio@hotmail.com");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(182, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(rSLabelHora1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JLogotipo, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(JLogotipo, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(rSLabelHora1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel21)
                .addGap(19, 19, 19))
        );

        jPanelSlider1.add(jPanel3, "card3");

        JPRegistroGalpones.setBackground(new java.awt.Color(255, 255, 255));
        JPRegistroGalpones.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        JPRegistroGalpones.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        jLabel5.setText("Número de Pollos");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(20, 140, 110, 15);

        jLabel6.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        jLabel6.setText("veces");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(710, 20, 40, 15);

        txtnumeropollo.setBorder(null);
        jPanel4.add(txtnumeropollo);
        txtnumeropollo.setBounds(160, 130, 140, 30);

        txtraza.setBorder(null);
        jPanel4.add(txtraza);
        txtraza.setBounds(160, 190, 150, 30);
        jPanel4.add(jSeparator2);
        jSeparator2.setBounds(160, 160, 150, 10);
        jPanel4.add(jSeparator3);
        jSeparator3.setBounds(160, 220, 150, 10);

        btnGuardar.setBackground(new java.awt.Color(255, 255, 255));
        btnGuardar.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGuardarMouseExited(evt);
            }
        });
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel4.add(btnGuardar);
        btnGuardar.setBounds(560, 420, 130, 40);

        btnActualizar.setBackground(new java.awt.Color(255, 255, 255));
        btnActualizar.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnActualizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnActualizarMouseExited(evt);
            }
        });
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel4.add(btnActualizar);
        btnActualizar.setBounds(340, 420, 110, 40);

        btnEliminar.setBackground(new java.awt.Color(255, 255, 255));
        btnEliminar.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarMouseExited(evt);
            }
        });
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel4.add(btnEliminar);
        btnEliminar.setBounds(70, 420, 140, 40);

        tablegalpones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablegalpones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablegalponesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablegalpones);

        jPanel4.add(jScrollPane2);
        jScrollPane2.setBounds(20, 270, 800, 120);

        jLabel8.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        jLabel8.setText("Tipo de Balanceado:");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(20, 20, 120, 15);

        cbTipoBalanceado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Engorde", "Crecimiento" }));
        jPanel4.add(cbTipoBalanceado);
        cbTipoBalanceado.setBounds(150, 10, 100, 30);
        jPanel4.add(jSeparator8);
        jSeparator8.setBounds(160, 90, 150, 10);

        txtCtdBalanceadoSuministrada.setBorder(null);
        jPanel4.add(txtCtdBalanceadoSuministrada);
        txtCtdBalanceadoSuministrada.setBounds(160, 60, 140, 30);

        jLabel9.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        jLabel9.setText("Cantidad Suministrada:");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(20, 70, 140, 15);

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel2.setText("Frecuencia Diaria de Alimentación:");
        jLabel2.setMaximumSize(new java.awt.Dimension(114, 16));
        jLabel2.setMinimumSize(new java.awt.Dimension(114, 16));
        jPanel4.add(jLabel2);
        jLabel2.setBounds(450, 20, 200, 16);

        cbFDAlimentacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4" }));
        jPanel4.add(cbFDAlimentacion);
        cbFDAlimentacion.setBounds(660, 10, 40, 30);

        jLabel17.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        jLabel17.setText("Raza");
        jPanel4.add(jLabel17);
        jLabel17.setBounds(20, 210, 40, 15);

        JPRegistroGalpones.add(jPanel4);
        jPanel4.setBounds(10, 40, 840, 470);

        jLabel3.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("REGISTRO DE GALPONES");
        JPRegistroGalpones.add(jLabel3);
        jLabel3.setBounds(300, 0, 240, 30);
        JPRegistroGalpones.add(txtid);
        txtid.setBounds(30, 10, 15, 24);

        jPanelSlider1.add(JPRegistroGalpones, "card2");

        JPRegistroVacuna.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.setLayout(null);

        txtnombreProducto.setBorder(null);
        jPanel2.add(txtnombreProducto);
        txtnombreProducto.setBounds(140, 40, 250, 30);
        jPanel2.add(jDate1);
        jDate1.setBounds(590, 160, 160, 30);
        jPanel2.add(jDate2);
        jDate2.setBounds(590, 200, 160, 30);
        jPanel2.add(jSeparator6);
        jSeparator6.setBounds(140, 30, 70, 10);

        jLabel18.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        jLabel18.setText("Tipo de Producto:");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(10, 90, 100, 15);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setText("Guardar");
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(140, 250, 100, 40);

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton7.setText("Abrir PDF");
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7);
        jButton7.setBounds(410, 250, 110, 40);

        jLabel19.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        jLabel19.setText("Galpón Seleccionado:");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(10, 10, 130, 15);

        jLabel23.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        jLabel23.setText("Próxima:");
        jPanel2.add(jLabel23);
        jLabel23.setBounds(490, 210, 80, 15);

        cbTipoFarmaco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fármaco", "Biológico" }));
        jPanel2.add(cbTipoFarmaco);
        cbTipoFarmaco.setBounds(140, 80, 120, 30);

        txfGalponSeleccionado.setEditable(false);
        txfGalponSeleccionado.setBackground(new java.awt.Color(255, 255, 255));
        txfGalponSeleccionado.setBorder(null);
        jPanel2.add(txfGalponSeleccionado);
        txfGalponSeleccionado.setBounds(140, 0, 60, 30);

        jLabel24.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        jLabel24.setText("Nombre Producto:");
        jPanel2.add(jLabel24);
        jLabel24.setBounds(10, 50, 120, 15);
        jPanel2.add(jSeparator10);
        jSeparator10.setBounds(140, 70, 250, 10);

        JtaJustificacion.setColumns(20);
        JtaJustificacion.setRows(5);
        jScrollPane1.setViewportView(JtaJustificacion);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(140, 130, 260, 100);

        txfDosis.setBackground(new java.awt.Color(255, 255, 255));
        txfDosis.setBorder(null);
        jPanel2.add(txfDosis);
        txfDosis.setBounds(620, 30, 60, 30);
        jPanel2.add(jSeparator7);
        jSeparator7.setBounds(620, 60, 70, 10);

        jLabel26.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        jLabel26.setText("Dosis:");
        jPanel2.add(jLabel26);
        jLabel26.setBounds(490, 40, 50, 15);

        cbMedidaDosis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "g", "mg", "ml" }));
        jPanel2.add(cbMedidaDosis);
        cbMedidaDosis.setBounds(710, 30, 60, 30);

        jLabel25.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        jLabel25.setText("Justificación:");
        jPanel2.add(jLabel25);
        jLabel25.setBounds(10, 130, 90, 15);

        jLabel27.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        jLabel27.setText("Administra:");
        jPanel2.add(jLabel27);
        jLabel27.setBounds(490, 90, 80, 15);

        jLabel28.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        jLabel28.setText("Primera:");
        jPanel2.add(jLabel28);
        jLabel28.setBounds(490, 170, 80, 15);

        jLabel29.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        jLabel29.setText("Fecha Vacunas");
        jPanel2.add(jLabel29);
        jLabel29.setBounds(610, 130, 110, 15);

        tablevacuna.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablevacuna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablevacunaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablevacuna);

        jPanel2.add(jScrollPane3);
        jScrollPane3.setBounds(20, 310, 820, 150);

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton8.setText("Actualizar");
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8);
        jButton8.setBounds(270, 250, 110, 40);

        jLabel16.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("REGISTRO DE VACUNAS");

        javax.swing.GroupLayout JPRegistroVacunaLayout = new javax.swing.GroupLayout(JPRegistroVacuna);
        JPRegistroVacuna.setLayout(JPRegistroVacunaLayout);
        JPRegistroVacunaLayout.setHorizontalGroup(
            JPRegistroVacunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPRegistroVacunaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtidvacuna, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 194, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(248, 248, 248))
            .addGroup(JPRegistroVacunaLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        JPRegistroVacunaLayout.setVerticalGroup(
            JPRegistroVacunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPRegistroVacunaLayout.createSequentialGroup()
                .addGroup(JPRegistroVacunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtidvacuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelSlider1.add(JPRegistroVacuna, "card4");

        Fondo2.add(jPanelSlider1);
        jPanelSlider1.setBounds(0, 0, 870, 520);

        Fondo1.add(Fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 860, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1101, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1101, 574));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        // TODO add your handling code here:
        xmouse = evt.getX();
        ymouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xmouse, y - ymouse);
    }//GEN-LAST:event_headerMouseDragged

    private void closetextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closetextMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closetextMouseClicked

    private void closetextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closetextMouseEntered
        // TODO add your handling code here:
        closetext.setForeground(Color.black);
        Cerrar.setBackground(Color.red);
        closetext.setForeground(Color.WHITE);
    }//GEN-LAST:event_closetextMouseEntered

    private void closetextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closetextMouseExited
        // TODO add your handling code here:
        Cerrar.setBackground(Color.white);
        closetext.setForeground(Color.black);
    }//GEN-LAST:event_closetextMouseExited

    private void BtnRegistroGalponMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnRegistroGalponMouseEntered
        BtnRegistroGalpon.setBackground(new Color(153, 153, 255));
        registroGalpontxt.setForeground(Color.WHITE);

    }//GEN-LAST:event_BtnRegistroGalponMouseEntered

    private void BtnRegistroGalponMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnRegistroGalponMouseExited
        // TODO add your handling code here:
        //[102,102,255]

        BtnRegistroGalpon.setBackground(new Color(102, 102, 255));
        registroGalpontxt.setForeground(Color.WHITE);

    }//GEN-LAST:event_BtnRegistroGalponMouseExited

    private void BtnRegistroGalponMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnRegistroGalponMouseClicked
        jPanelSlider1.nextPanel(4, 0, JPRegistroGalpones, jPanelSlider1.right);
    }//GEN-LAST:event_BtnRegistroGalponMouseClicked

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        Updategalpon();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        guardarGalpon();

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void JPVacunaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPVacunaMouseClicked
        // TODO add your handling code here:
        jPanelSlider1.nextPanel(4, 0, JPRegistroVacuna, jPanelSlider1.right);
    }//GEN-LAST:event_JPVacunaMouseClicked

    private void JPVacunaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPVacunaMouseEntered
        // TODO add your handling code here:
        JPVacuna.setBackground(new Color(153, 153, 255));
        vacunatxt.setForeground(Color.WHITE);
    }//GEN-LAST:event_JPVacunaMouseEntered

    private void JPVacunaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPVacunaMouseExited
        // TODO add your handling code here:
        JPVacuna.setBackground(new Color(102, 102, 255));
        vacunatxt.setForeground(Color.WHITE);
    }//GEN-LAST:event_JPVacunaMouseExited

    private void btnGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseEntered
        // TODO add your handling code here:
        btnGuardar.setBackground(new Color(153, 153, 255));
    }//GEN-LAST:event_btnGuardarMouseEntered

    private void btnGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseExited
        // TODO add your handling code here:
        btnGuardar.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnGuardarMouseExited

    private void btnActualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMouseEntered
        // TODO add your handling code here:
        btnActualizar.setBackground(new Color(153, 153, 255));
    }//GEN-LAST:event_btnActualizarMouseEntered

    private void btnActualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMouseExited
        btnActualizar.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnActualizarMouseExited

    private void btnEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseEntered
        btnEliminar.setBackground(new Color(153, 153, 255));
    }//GEN-LAST:event_btnEliminarMouseEntered

    private void btnEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseExited
        btnEliminar.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnEliminarMouseExited

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            guardarVacuna();
            generarPDF();
            limpiardatosVacuna();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Frm_PrincipalDemo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(Frm_PrincipalDemo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        deleteGalpon();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tablegalponesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablegalponesMouseClicked
        seleccionar();
    }//GEN-LAST:event_tablegalponesMouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        updateVacuna();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void tablevacunaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablevacunaMouseClicked
        seleccionarVacuna();
    }//GEN-LAST:event_tablevacunaMouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        abrirpdf();
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_PrincipalDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_PrincipalDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_PrincipalDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_PrincipalDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Frm_PrincipalDemo dialog = new Frm_PrincipalDemo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private void cargarTableGalpon() {
        modeloG.setLista(galponController.listar());
        tcr.setHorizontalAlignment(SwingConstants.CENTER);
        for (int i = 0; i < tablegalpones.getColumnCount(); i++) {
            tablegalpones.getColumnModel().getColumn(i).setHeaderRenderer(tcr);
            tablegalpones.getColumnModel().getColumn(i).setCellRenderer(tcr);
            tablegalpones.setModel(modeloG);

        }
        tablegalpones.updateUI();

    }

    private void generarPDF() throws FileNotFoundException, DocumentException{
        if (!(txfGalponSeleccionado.getText().trim().isEmpty()
                || txtnombreProducto.getText().trim().isEmpty()
                || JtaJustificacion.getText().trim().isEmpty()
                || txfDosis.getText().trim().isEmpty())) {
            String galpon = txfGalponSeleccionado.getText().trim();
            FileOutputStream archivo = new FileOutputStream("Registro_Vacuna_Galpon_" + galpon + ".pdf", true);
            Document document = new Document();
            PdfWriter.getInstance(document, archivo);
            document.open();

            Paragraph paragraph = new Paragraph("Registro de Vacuna");
            paragraph.setAlignment(1);
            document.add(paragraph);
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            document.add(new Paragraph("Galpón: " + txfGalponSeleccionado.getText().trim()));
            document.add(new Paragraph("Nombre del Producto: " + txtnombreProducto.getText().trim()));
            document.add(new Paragraph("Tipo de Producto: " + String.valueOf(cbTipoFarmaco.getSelectedItem())));
            document.add(new Paragraph("Dosis: " + txfDosis.getText().trim() + String.valueOf(cbMedidaDosis.getSelectedItem())));
            document.add(new Paragraph("Justificación: " + JtaJustificacion.getText().trim()));
            document.add(new Paragraph("Primera Inyección: " + sdf.format(jDate1.getDate())));
            document.add(new Paragraph("Próxima Inyección: " + sdf.format(jDate2.getDate())));
            document.close();
            //JOptionPane.showMessageDialog(null, "Archivo PDF creado correctamente", "Informacion", 1);
            
        } else {
            //JOptionPane.showMessageDialog(null, "Debe tener llenos todos los campos", "Atencion", 2);
        }
    }
    private void abrirpdf(){
        String galpon = txfGalponSeleccionado.getText().trim();
        try {
            File path = new File("Registro_Vacuna_Galpon_" + galpon + ".pdf");
            Desktop.getDesktop().open(path);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "Atencion", 2);
        }

    }

    private void cargarTableVacuna() {
        modelov.setLista(vacunaController.listar());
        tcr.setHorizontalAlignment(SwingConstants.CENTER);
        for (int i = 0; i < tablevacuna.getColumnCount(); i++) {
            tablevacuna.getColumnModel().getColumn(i).setHeaderRenderer(tcr);
            tablevacuna.getColumnModel().getColumn(i).setCellRenderer(tcr);
            tablevacuna.setModel(modelov);
        }
        tablevacuna.updateUI();
    }

    private void seleccionar() {
        try {
            this.txtid.setText(tablegalpones.getValueAt(tablegalpones.getSelectedRow(), 0).toString());
            this.txtnumeropollo.setText(tablegalpones.getValueAt(tablegalpones.getSelectedRow(), 1).toString());
            this.txtraza.setText(tablegalpones.getValueAt(tablegalpones.getSelectedRow(), 2).toString());
            this.txtCtdBalanceadoSuministrada.setText(tablegalpones.getValueAt(tablegalpones.getSelectedRow(), 3).toString());
            this.cbTipoBalanceado.setSelectedItem(tablegalpones.getValueAt(tablegalpones.getSelectedRow(), 4).toString());
            this.cbFDAlimentacion.setSelectedItem(tablegalpones.getValueAt(tablegalpones.getSelectedRow(), 5).toString());
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    private void seleccionarVacuna() {
        SimpleDateFormat st = new SimpleDateFormat("yyyy-MM-dd");
        String primeraVacuna = tablevacuna.getValueAt(tablevacuna.getSelectedRow(), 5).toString();
        Date fechaprimera = null;
        String segundaVacuna = tablevacuna.getValueAt(tablevacuna.getSelectedRow(), 6).toString();
        Date fechasegunda = null;
        try {
            fechaprimera = st.parse(primeraVacuna);
            fechasegunda = st.parse(segundaVacuna);
            this.txtidvacuna.setText(tablevacuna.getValueAt(tablevacuna.getSelectedRow(), 0).toString());
            this.txtnombreProducto.setText(tablevacuna.getValueAt(tablevacuna.getSelectedRow(), 1).toString());
            this.cbTipoFarmaco.setSelectedItem(tablevacuna.getValueAt(tablevacuna.getSelectedRow(), 2).toString());
            this.JtaJustificacion.setText(tablevacuna.getValueAt(tablevacuna.getSelectedRow(), 3).toString());
            this.txfDosis.setText(tablevacuna.getValueAt(tablevacuna.getSelectedRow(), 4).toString());
            this.jDate1.setDate(fechaprimera);
            this.jDate2.setDate(fechasegunda);

        } catch (Exception e) {
        }
    }

    public void poputTable() {
        JPopupMenu popuMenu = new JPopupMenu();
        JMenuItem menuItem1 = new JMenuItem("Aplicar Vacuna", new ImageIcon(getClass().getResource("/Image/vacuna.png")));
        menuItem1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                jPanelSlider1.nextPanel(4, 0, JPRegistroVacuna, jPanelSlider1.right);
                int fila = tablegalpones.getSelectedRow();
                JPRegistroVacuna.setVisible(true);
                txfGalponSeleccionado.setText(tablegalpones.getValueAt(fila, 0).toString());

            }
        });
        popuMenu.add(menuItem1);
        tablegalpones.setComponentPopupMenu(popuMenu);
    }

    private void limpiardatosGalpon() {
        txtCtdBalanceadoSuministrada.setText("");
        txtnumeropollo.setText("");
        txtraza.setText("");
        galponController.setGalpon(null);
        //cargarTableGalpon();
    }

    private void limpiardatosVacuna() {
        txtnombreProducto.setText(" ");
        JtaJustificacion.setText(" ");
        jDate1.setDate(new Date());
        jDate2.setDate(new Date());
        vacunaController.setVacuna(null);
        //cargarTableVacuna();
    }

    private void guardarGalpon() {
        if (txtnumeropollo.getText().trim().isEmpty() || txtraza.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Llene todos los campos", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            galponController.getGalpon().setNumPollo(txtnumeropollo.getText());
            galponController.getGalpon().setRaza(txtraza.getText());
            galponController.getGalpon().setCtdSuministrada(Integer.parseInt(txtCtdBalanceadoSuministrada.getText().trim()));
            galponController.getGalpon().setTbalanceado(String.valueOf(cbTipoBalanceado.getSelectedItem()));
            galponController.getGalpon().setfDiarioAlimentacion(Integer.parseInt(String.valueOf(cbFDAlimentacion.getSelectedItem())));
            if (galponController.Save()) {
                JOptionPane.showMessageDialog(null, "Se guardo correctamente", "Ok", JOptionPane.INFORMATION_MESSAGE);
                limpiardatosGalpon();
            } else {
                JOptionPane.showMessageDialog(null, "Error al guardar", "Error", JOptionPane.ERROR_MESSAGE);
            }
            cargarTableGalpon();
        }
    }

    private void guardarVacuna(){
        if (txtnombreProducto.getText().trim().isEmpty() || txfDosis.getText().trim().isEmpty()
                || cbTipoFarmaco.getSelectedItem() == null || JtaJustificacion.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Llene todos los campos", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            vacunaController.getVacuna().setNombre(txtnombreProducto.getText());
            vacunaController.getVacuna().setFarmaco(String.valueOf(cbTipoFarmaco.getSelectedItem()));
            vacunaController.getVacuna().setJustificacion(JtaJustificacion.getText().trim());
            vacunaController.getVacuna().setDosis(Double.parseDouble(txfDosis.getText()));
            vacunaController.getVacuna().setOnevacuna(jDate1.getDate());
            vacunaController.getVacuna().setTwovacuna(jDate2.getDate());
            if (vacunaController.Save()) {
                JOptionPane.showMessageDialog(null, "Guardado", "Ok", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Error al guardar", "Error", JOptionPane.ERROR_MESSAGE);
            }
            cargarTableVacuna();
        }
    }

    private void updateVacuna() {
        vacunaController.getVacuna().setId_vacuna(Integer.parseInt(txtidvacuna.getText()));
        vacunaController.getVacuna().setNombre(txtnombreProducto.getText());
        vacunaController.getVacuna().setFarmaco(String.valueOf(cbTipoFarmaco.getSelectedItem()));
        vacunaController.getVacuna().setJustificacion(JtaJustificacion.getText().trim());
        vacunaController.getVacuna().setDosis(Double.parseDouble(txfDosis.getText()));
        vacunaController.getVacuna().setOnevacuna(jDate1.getDate());
        vacunaController.getVacuna().setTwovacuna(jDate2.getDate());
        if (vacunaController.Update()) {
            JOptionPane.showMessageDialog(null, "Se modifico correctamente", "Ok", JOptionPane.INFORMATION_MESSAGE);
            limpiardatosVacuna();
        } else {
            JOptionPane.showMessageDialog(null, "Error al modificar", "Error", JOptionPane.ERROR_MESSAGE);
        }
        cargarTableVacuna();
    }

    private void Updategalpon() {
        galponController.getGalpon().setId(Integer.parseInt(txtid.getText()));
        galponController.getGalpon().setNumPollo(txtnumeropollo.getText());
        galponController.getGalpon().setRaza(txtraza.getText());
        galponController.getGalpon().setCtdSuministrada(Integer.parseInt(txtCtdBalanceadoSuministrada.getText().trim()));
        galponController.getGalpon().setTbalanceado(String.valueOf(cbTipoBalanceado.getSelectedItem()));
        galponController.getGalpon().setfDiarioAlimentacion(Integer.parseInt(String.valueOf(cbFDAlimentacion.getSelectedItem())));
        if (galponController.Update()) {
            JOptionPane.showMessageDialog(null, "Se modifico correctamente", "Ok", JOptionPane.INFORMATION_MESSAGE);
            limpiardatosGalpon();
        } else {
            JOptionPane.showMessageDialog(null, "Error al modificar", "Error", JOptionPane.ERROR_MESSAGE);
        }
        cargarTableGalpon();

    }

    private void deleteGalpon() {
        int seleccionar = tablegalpones.getSelectedRow();
        if (seleccionar == -1) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una fila", "Advertencia", JOptionPane.WARNING_MESSAGE);
        } else {
            galponController.getGalpon().setId(Integer.parseInt(txtid.getText()));
            if (galponController.Delete()) {
                JOptionPane.showMessageDialog(null, "galpon eliminado exitosamente");
                limpiardatosGalpon();
            } else {
                JOptionPane.showMessageDialog(null, "Error al eliminar");
            }
            cargarTableGalpon();
        }
    }

    class fondoPaneles extends JPanel {

        private Image pollo;

        @Override
        public void paint(Graphics g) {
            pollo = new ImageIcon(getClass().getResource("/Image/fondo-granja.png")).getImage();
            g.drawImage(pollo, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }

    }

    class fondoLabel extends JLabel {

        private Image logo;

        @Override
        public void paint(Graphics g) {
            logo = new ImageIcon(getClass().getResource("/Image/logotipo-granja.png")).getImage();
            g.drawImage(logo, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BtnRegistroGalpon;
    private javax.swing.JPanel Cerrar;
    private javax.swing.JPanel Fondo1;
    private javax.swing.JPanel Fondo2;
    private javax.swing.JLabel JLogotipo;
    private javax.swing.JPanel JPRegistroGalpones;
    private javax.swing.JPanel JPRegistroVacuna;
    private javax.swing.JPanel JPVacuna;
    private javax.swing.JTextArea JtaJustificacion;
    private javax.swing.JPanel Navegador;
    private javax.swing.JPanel Title;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cbFDAlimentacion;
    private javax.swing.JComboBox<String> cbMedidaDosis;
    private javax.swing.JComboBox<String> cbTipoBalanceado;
    private javax.swing.JComboBox<String> cbTipoFarmaco;
    private javax.swing.JLabel closetext;
    private javax.swing.JPanel header;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private com.toedter.calendar.JDateChooser jDate1;
    private com.toedter.calendar.JDateChooser jDate2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private diu.swe.habib.JPanelSlider.JPanelSlider jPanelSlider1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private rojeru_san.RSLabelHora rSLabelHora1;
    private javax.swing.JLabel registroGalpontxt;
    private javax.swing.JTable tablegalpones;
    private javax.swing.JTable tablevacuna;
    private javax.swing.JTextField txfDosis;
    private javax.swing.JTextField txfGalponSeleccionado;
    private javax.swing.JTextField txtCtdBalanceadoSuministrada;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtidvacuna;
    private javax.swing.JTextField txtnombreProducto;
    private javax.swing.JTextField txtnumeropollo;
    private javax.swing.JTextField txtraza;
    private javax.swing.JLabel vacunatxt;
    // End of variables declaration//GEN-END:variables
}
