/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.VacunaController;
import View.Table.TableVacuna;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Home
 */
public class Frm_Vacunas extends javax.swing.JFrame {
    private VacunaController vacunaController = new VacunaController();
    private TableVacuna modelo = new TableVacuna();

    /**
     * Creates new form Frm_Vacunas
     */
    public Frm_Vacunas() {
        super("Vacunas");
        setResizable(false);
        initComponents();
        setLocationRelativeTo(null);
    }
    private void cargarTable() {
        modelo.setLista(vacunaController.listar());
        tablevacuna.setModel(modelo);
        tablevacuna.updateUI();
    }
    private void limpiardatos() {
        txtnombre.setText(" ");
        txtfarmaco.setText(" ");
        txtvitamina.setText(" ");
        jDate1.setDate(new Date());
        jDate2.setDate(new Date());
        vacunaController.setVacuna(null);
        cargarTable();
    }
    private void guardar() {
        if (txtnombre.getText().trim().isEmpty() || txtfarmaco.getText().trim().isEmpty()
                || txtvitamina.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Llene todos los campos", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            vacunaController.getVacuna().setNombre(txtnombre.getText());
            vacunaController.getVacuna().setFarmaco(txtfarmaco.getText());
            vacunaController.getVacuna().setVitamina(txtvitamina.getText());
            vacunaController.getVacuna().setOnevacuna(jDate1.getDate());
            vacunaController.getVacuna().setTwovacuna(jDate2.getDate());
            if (vacunaController.getVacuna().getId() == null) {
                if (vacunaController.Save()) {
                    JOptionPane.showMessageDialog(null, "Se guardo` correctamente", "Ok", JOptionPane.INFORMATION_MESSAGE);
                    limpiardatos();
                } else {
                    JOptionPane.showMessageDialog(null, "Error al guardar", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
            //ciudadController.getCiudad().setId(new Long(ciudadController.listar().tamanio() + 1));
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtnum = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtvitamina = new javax.swing.JTextField();
        txtfarmaco = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        jDate1 = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jDate2 = new com.toedter.calendar.JDateChooser();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablevacuna = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 102, 0));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("REGISTRO DE VACUNAS");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(280, 10, 260, 24);
        jPanel1.add(txtnum);
        txtnum.setBounds(120, 50, 40, 24);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Numero Galpon");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 50, 120, 19);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        jLabel3.setText("Fechas de vacunas");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(240, 20, 107, 20);

        jLabel4.setText("Nombre:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 20, 50, 16);

        jLabel5.setText("Farmaco:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 60, 50, 16);

        jLabel6.setText("Vitamina:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 110, 50, 16);
        jPanel2.add(txtvitamina);
        txtvitamina.setBounds(70, 110, 90, 24);
        jPanel2.add(txtfarmaco);
        txtfarmaco.setBounds(70, 60, 90, 24);
        jPanel2.add(txtnombre);
        txtnombre.setBounds(70, 20, 90, 24);
        jPanel2.add(jDate1);
        jDate1.setBounds(240, 50, 130, 24);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Tabla.png"))); // NOI18N
        jPanel2.add(jButton1);
        jButton1.setBounds(290, 160, 50, 40);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/guardar.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(20, 160, 50, 40);

        jLabel7.setText("Segunda");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(180, 90, 50, 20);

        jLabel8.setText("Primera");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(180, 50, 50, 20);
        jPanel2.add(jDate2);
        jDate2.setBounds(240, 90, 130, 24);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/acualizar.png"))); // NOI18N
        jPanel2.add(jButton3);
        jButton3.setBounds(140, 160, 50, 40);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel9.setText("Generar PDF");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(130, 200, 80, 16);

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel11.setText("Ver Registro");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(280, 200, 80, 16);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 80, 380, 240);

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(null);

        tablevacuna.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablevacuna);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(10, 20, 320, 190);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(400, 80, 340, 240);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 750, 330);

        setSize(new java.awt.Dimension(760, 368));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        guardar();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Vacunas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Vacunas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Vacunas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Vacunas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Vacunas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jDate1;
    private com.toedter.calendar.JDateChooser jDate2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablevacuna;
    private javax.swing.JTextField txtfarmaco;
    private javax.swing.JTextField txtnombre;
    public static javax.swing.JTextField txtnum;
    private javax.swing.JTextField txtvitamina;
    // End of variables declaration//GEN-END:variables
}
